#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────────────
# build-blocks.py — shard WSI Radio's master metadata into per-block
# files so the Player only loads what a random block needs at boot.
#
# Run:   python build-blocks.py
#
# First run
# ─────────
#   Reads  cf-signal.dat  (master, hand-edited; you already have this).
#   Reads  tracks/cf-rhythm.dat  (generated by analyze-beats.py).
#   Reads  track-links.dat  +  tracks/scan-skip.dat  (if present).
#   Emits  blocks/index.dat  +  blocks/globals.dat  +  blocks/bNN-*.dat.
#   Renames cf-signal.dat → cf-signal-master.dat  (archive; read-only from here on).
#   Renames track-links.dat → track-links-master.dat  (same).
#
# Subsequent runs (shards are the editable source)
# ────────────────────────────────────────────────
#   Reads every blocks/bNN-signal.dat shard directly.
#   Detects misplaced tracks (td-audio007 living in b02 when it belongs in b01):
#     · duplicate (same track, identical content in both): remove the misplaced copy
#     · conflict  (same track, DIFFERENT content): keep the rightful home's version,
#       insert the offending copy into the rightful block as commented-out lines
#       (each line prefixed with "# CONFLICT: "), remove the misplaced copy,
#       and print a warning so you know to look at it.
#   Re-shards rhythm / links / skip from their masters.
#   Regenerates blocks/index.dat.
#
# Block math: block = ceil(track_num / 10).
#   td-audio001..010 → block 1
#   td-audio011..020 → block 2
#   ...
#
# Format preservation
# ───────────────────
# Signal shards are sliced byte-by-byte on ===== separator lines, so all your
# formatting (# blank comments, `# NNN` headers, `──── section ── NNN` dividers,
# closing ====== line) survives round-trips untouched. The script never
# re-emits a parsed representation of the signal block — it just moves text
# chunks between files.
# ─────────────────────────────────────────────────────────────────

import sys
import re
import shutil
from pathlib import Path
from collections import defaultdict

# Force UTF-8 on stdout so Windows cp1252 consoles don't choke on the arrow
# characters + block separators we print. `reconfigure` is Python 3.7+.
try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass


HERE = Path(__file__).resolve().parent

# ── Inputs (masters) ──────────────────────────────────────────
SIGNAL_MASTER         = HERE / "cf-signal.dat"
SIGNAL_MASTER_RENAMED = HERE / "cf-signal-master.dat"
LINKS_MASTER          = HERE / "track-links.dat"
LINKS_MASTER_RENAMED  = HERE / "track-links-master.dat"
RHYTHM_MASTER         = HERE / "tracks" / "cf-rhythm.dat"
SKIP_MASTER           = HERE / "tracks" / "scan-skip.dat"

# ── Outputs ───────────────────────────────────────────────────
BLOCKS_DIR     = HERE / "blocks"
INDEX_FILE     = BLOCKS_DIR / "index.dat"
GLOBALS_FILE   = BLOCKS_DIR / "globals.dat"

# ── Regexes ───────────────────────────────────────────────────
SEP_LINE_RE   = re.compile(r"(?m)^={5,}[ \t]*\r?\n?")
TRACK_ID_RE   = re.compile(r"td-audio(\d+)", re.I)
# `[ \t]*` deliberately — using `\s*` would span newlines and greedily eat the
# next line's contents when a placeholder block has empty `File:` entries.
FILE_LINE_RE  = re.compile(r"^File[ \t]*:[ \t]*(\S+)", re.I | re.M)
SUFFIX_RE     = re.compile(r"-(?:normal|high|off)\.(?:mp3|wav)$", re.I)

BLOCK_SIZE = 10

# A placeholder block is one with no derivable track-id (no `File:` line with
# a td-audioNNN filename). Authors keep these as scaffolds so adding a new
# track is "fill in the blank" rather than "paste the whole frame". Detected
# by the absence of `tid` on a parsed track dict.
PLACEHOLDER_HEADER_RE = re.compile(r"^\s*#\s*(\d+)\s*$", re.MULTILINE)


def _is_placeholder(t):
    return not t.get("tid")


def _placeholder_hinted_num(t):
    """Scan the placeholder's preamble for a `# NNN` header line (author's
    way of noting the intended track number). Returns int or None."""
    m = PLACEHOLDER_HEADER_RE.search(t.get("preamble") or "")
    if not m:
        return None
    try:
        return int(m.group(1))
    except ValueError:
        return None


def _placeholder_block_for(t):
    """Best-guess block number for a placeholder. Uses the `# NNN` header
    hint if present, falls back to block 1."""
    n = _placeholder_hinted_num(t)
    if n is None:
        return 1
    return ((n - 1) // BLOCK_SIZE) + 1


# ═════════════════════════════════════════════════════════════════
# Helpers
# ═════════════════════════════════════════════════════════════════

def read_text(path: Path):
    if not path.exists():
        return None
    # Use newline='' so we can preserve the original CRLF/LF mix on write.
    with path.open("r", encoding="utf-8", newline="") as fh:
        return fh.read()


def write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        fh.write(text)


def detect_newline(text: str):
    """Return the first line terminator found in the file, or '\\n' as default."""
    if "\r\n" in text:
        return "\r\n"
    if "\n" in text:
        return "\n"
    return "\n"


def track_id_from_filename(filename: str):
    """`td-audio007-normal.mp3` → `td-audio007`."""
    return SUFFIX_RE.sub("", filename.strip())


def track_num(tid: str):
    """`td-audio007` → 7. Returns None when tid has no numeric suffix."""
    if not tid:
        return None
    m = TRACK_ID_RE.search(tid)
    return int(m.group(1)) if m else None


def block_for(tid: str):
    """1-indexed block: td-audio001..010→1, 011..020→2, etc. None for malformed ids."""
    n = track_num(tid)
    if n is None:
        return None
    return ((n - 1) // BLOCK_SIZE) + 1


def shard_name(kind: str, block: int):
    """kind ∈ {signal, rhythm, links, skip}; block is 1-indexed int."""
    return f"b{block:02d}-{kind}.dat"


# ═════════════════════════════════════════════════════════════════
# Signal parse (block-preserving)
# ═════════════════════════════════════════════════════════════════
#
# A signal file has this shape:
#
#     <header comments>
#     =====
#     <globals body>
#     =====
#     <preamble1>
#     =====
#     <body1>
#     =====
#     <preamble2>
#     =====
#     <body2>
#     =====
#     ...
#
# Shards omit the globals pair — they just go header / preamble / body / preamble / body.
# We read by splitting on ===== lines. The resulting `parts` alternate:
#     parts[0] = leading text (header comments)
#     parts[1] = globals body (master) OR first-track preamble (shard)
#     parts[2] = first-track preamble (master) OR first-track body (shard)
#     parts[3] = first-track body (master)  OR second-track preamble (shard)
#     ...
# The caller tells us whether this is a master or a shard via `has_globals`.

def split_on_sep(text: str):
    """Split the text on each ===== separator line. Returns a list of chunks (no
    separator text included) — order-preserving, so re-joining with the original
    separator line reconstructs the file exactly."""
    if not text:
        return []
    return SEP_LINE_RE.split(text)


def join_with_sep(chunks, sep_line: str):
    """Inverse of split_on_sep. sep_line includes its own terminator."""
    out = []
    for i, chunk in enumerate(chunks):
        if i > 0:
            out.append(sep_line)
        out.append(chunk)
    return "".join(out)


def detect_sep_line(text: str):
    """Preserve the exact separator line the source uses (length + line ending)."""
    m = SEP_LINE_RE.search(text or "")
    return m.group(0) if m else "=================================================================\n"


def parse_signal(text: str, has_globals: bool):
    """Parse a master (has_globals=True) or shard (has_globals=False) signal file.

    Returns (header, globals_text_or_None, [{'preamble', 'body', 'tid', 'num'}, ...],
             trailer_text_or_empty)."""
    if not text:
        return "", None, [], ""

    parts = split_on_sep(text)
    # parts[0] is the leading text (file header comments) before the first =====.
    header = parts[0] if parts else ""
    rest = parts[1:]

    globals_text = None
    if has_globals and rest:
        globals_text = rest[0]
        rest = rest[1:]

    # Now rest alternates: preamble, body, preamble, body, ... [trailer_if_odd]
    tracks = []
    i = 0
    while i + 1 < len(rest):
        preamble = rest[i]
        body = rest[i + 1]
        # Find the first File: line to derive the track id.
        tid = None
        m = FILE_LINE_RE.search(body)
        if m:
            tid = track_id_from_filename(m.group(1))
        tracks.append({
            "preamble": preamble,
            "body": body,
            "tid": tid,
            "num": track_num(tid) if tid else None,
        })
        i += 2

    # Dangling trailer (odd number of chunks) preserves any trailing text
    # after the final =====. Usually empty for well-formed files.
    trailer = rest[i] if i < len(rest) else ""
    return header, globals_text, tracks, trailer


# Matches any field line whose key begins with `offline.` OR the legacy
# `<field>_offline` / `offline_file` forms. These lived in the master so a
# single signal.dat carried both online + offline variants, but v1 splits
# cfded into its own self-contained file — online/local shards no longer
# carry offline.* at all. Strip at emit time so the rule is enforced on
# every build, even when authors paste legacy blocks back into a shard.
OFFLINE_FIELD_RE = re.compile(
    r"^[ \t]*(?:offline\.\w[\w.\-]*|\w[\w.\-]*_offline|offline_file)[ \t]*=.*(?:\r?\n)?",
    re.MULTILINE | re.IGNORECASE,
)

def _strip_offline_lines(text: str) -> str:
    """Remove every `offline.*=` / `<field>_offline=` / `offline_file=` line
    from a track body. Preserves the body's surrounding layout — only the
    matched lines + their own trailing newline disappear."""
    if not text:
        return text
    return OFFLINE_FIELD_RE.sub("", text)


def emit_signal_shard(header: str, tracks: list, sep_line: str) -> str:
    """Build a shard signal file from a list of track dicts (preamble+body).
    No globals in shards — globals live in blocks/globals.dat.
    `offline.*` field lines are stripped so online/local shards stay lean."""
    if not tracks:
        return header  # shard with no tracks — unusual but harmless
    parts = [header]
    for t in tracks:
        parts.append(_strip_offline_lines(t["preamble"]))
        parts.append(_strip_offline_lines(t["body"]))
    # Add a trailing sep so the last ===== closes the final track's body.
    text = join_with_sep(parts, sep_line) + sep_line
    return text


def emit_globals(header: str, globals_text: str, sep_line: str) -> str:
    """blocks/globals.dat — the globals block extracted from the master. Same
    wrapping convention the master uses so the existing parser eats it fine."""
    return join_with_sep([header, globals_text], sep_line) + sep_line


# ═════════════════════════════════════════════════════════════════
# Conflict / duplicate reconciliation across shards
# ═════════════════════════════════════════════════════════════════

def _track_fingerprint(t):
    """Stable equality on track content (preamble + body). Used to detect
    identical duplicates so we can drop them silently."""
    return (t["preamble"].strip(), t["body"].strip())


def reconcile(tracks_by_block: dict):
    """Walk every (observed_block, track) pair. Move anything misplaced to its
    rightful block. On conflict, quote the loser as `# CONFLICT: ` comments in
    the rightful block and drop the duplicate copy. Mutates tracks_by_block
    in place.

    Returns a list of warning strings for the caller to print."""
    warnings = []
    # Fixed-point: keep iterating until no moves happen. Because a move can in
    # turn surface a conflict with a track already in the destination block.
    for _ in range(10):  # generous ceiling; pathological inputs bail out
        moved_any = False
        for observed_block in list(tracks_by_block.keys()):
            bucket = tracks_by_block[observed_block]
            keep = []
            for t in bucket:
                # Placeholder scaffolds — no tid, nothing to reconcile. Stay put.
                if _is_placeholder(t):
                    keep.append(t)
                    continue
                correct = block_for(t["tid"])
                if correct is None:
                    # Unresolvable track id — leave it where we found it and warn.
                    warnings.append(
                        f"[warn] {t['tid']} has no numeric id; "
                        f"leaving in b{observed_block:02d}"
                    )
                    keep.append(t)
                    continue
                if correct == observed_block:
                    keep.append(t)
                    continue
                # Misplaced — need to move to `correct`.
                dest = tracks_by_block.setdefault(correct, [])
                dup = next((x for x in dest if x["tid"] == t["tid"]), None)
                if dup is None:
                    # Clean move. Warn so the user knows the script rebalanced them.
                    warnings.append(
                        f"[move] {t['tid']}: b{observed_block:02d} → "
                        f"b{correct:02d} (rightful home)"
                    )
                    dest.append(t)
                    moved_any = True
                    # don't keep in source
                    continue
                # Destination already has this track.
                if _track_fingerprint(dup) == _track_fingerprint(t):
                    warnings.append(
                        f"[dup] {t['tid']}: identical copy in b{observed_block:02d} "
                        f"AND b{correct:02d} — removed the b{observed_block:02d} copy"
                    )
                    moved_any = True   # dropped, don't keep in source
                    continue
                # True conflict — same id, different content. Quote offender
                # into dest as commented-out lines and warn loudly.
                warnings.append(
                    f"[CONFLICT] {t['tid']}: b{correct:02d} already has this "
                    f"track with DIFFERENT content than b{observed_block:02d}'s "
                    f"copy. Kept b{correct:02d}'s version, commented-quoted the "
                    f"b{observed_block:02d} copy underneath it for you to review."
                )
                _quote_conflict_into_block(dest, dup, t, observed_block)
                moved_any = True
                continue
            tracks_by_block[observed_block] = keep
        if not moved_any:
            break
    # Drop emptied blocks.
    for block in list(tracks_by_block.keys()):
        if not tracks_by_block[block]:
            del tracks_by_block[block]
    # Sort each block by track number ascending.
    for block in tracks_by_block:
        tracks_by_block[block].sort(key=lambda t: t.get("num") or 10**9)
    return warnings


def _quote_conflict_into_block(dest_bucket, keeper, loser, loser_observed_block):
    """Append a `# CONFLICT: `-prefixed quote of `loser`'s preamble+body to the
    `keeper` track's body so the next re-shard run surfaces the mismatch visibly
    in the canonical block's signal shard."""
    header = (
        f"\n# "
        f"─────────────────────────── CONFLICT — from b{loser_observed_block:02d} "
        f"─ review ─\n"
    )
    quoted_preamble = "".join("# CONFLICT: " + line if line else "# CONFLICT:\n"
                              for line in loser["preamble"].splitlines(keepends=True))
    quoted_body = "".join("# CONFLICT: " + line if line else "# CONFLICT:\n"
                          for line in loser["body"].splitlines(keepends=True))
    footer = f"# ─────────────────────────── END CONFLICT ─────\n"
    keeper["body"] = (
        keeper["body"].rstrip("\r\n") + header + quoted_preamble + quoted_body + footer
    )


# ═════════════════════════════════════════════════════════════════
# Rhythm / links / skip sharding — simpler (line-based + block-based)
# ═════════════════════════════════════════════════════════════════

def shard_rhythm(rhythm_text: str, blocks_present_tids: dict) -> dict:
    """Slice cf-rhythm.dat (one line per track-id) into per-block shards.

    blocks_present_tids: { block → set(tids) } — only includes tracks whose
    block we actually emit a signal shard for. Rhythm entries for orphan tids
    (tracks in rhythm.dat but not in any signal shard) still get placed by
    their track-id's natural block, so the Player's orphan-fallback works."""
    shards = defaultdict(list)     # block → list of lines (with trailing newline preserved)
    if not rhythm_text:
        return {}
    for raw in rhythm_text.splitlines(keepends=True):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        tid = stripped.split(":", 1)[0]
        b = block_for(tid)
        if b is None:
            continue
        shards[b].append(raw if raw.endswith("\n") else raw + "\n")
    return {k: "".join(v) for k, v in shards.items()}


def shard_skip(skip_text: str) -> dict:
    """tracks/scan-skip.dat is one line per track: `<tid>; skip(secN); skip(secM)`"""
    shards = defaultdict(list)
    if not skip_text:
        return {}
    for raw in skip_text.splitlines(keepends=True):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        tid = stripped.split(";", 1)[0].strip()
        b = block_for(tid)
        if b is None:
            continue
        shards[b].append(raw if raw.endswith("\n") else raw + "\n")
    return {k: "".join(v) for k, v in shards.items()}


def shard_links(links_text: str) -> dict:
    """track-links.dat is a multi-line-per-track file with its own separator
    convention. We use the file's ===== or blank-line separation to keep
    whole per-track blocks together. Each block starts with an id= line."""
    shards = defaultdict(list)
    if not links_text:
        return {}
    # The existing parser treats each `id=<tid>` line as the start of a new
    # track block. Split by lines; accumulate until the next id= line.
    current_tid = None
    current_lines = []
    out_per_tid = {}

    def flush():
        nonlocal current_tid, current_lines
        if current_tid and current_lines:
            out_per_tid[current_tid] = "".join(current_lines)
        current_tid, current_lines = None, []

    for raw in links_text.splitlines(keepends=True):
        s = raw.strip()
        if s.startswith("id=") or s.startswith("id ="):
            flush()
            current_tid = s.split("=", 1)[1].strip()
            current_lines.append(raw)
        else:
            current_lines.append(raw)
    flush()
    for tid, block_text in out_per_tid.items():
        b = block_for(tid)
        if b is None:
            continue
        shards[b].append(block_text)
    return {k: "".join(v) for k, v in shards.items()}


# ═════════════════════════════════════════════════════════════════
# Main
# ═════════════════════════════════════════════════════════════════

def gather_signal_tracks():
    """Return (header, globals_text, sep_line, tracks_by_block:dict, source:str).

    Source is "shards" (second+ run, shards exist) or "master" (first run)."""
    # Prefer shards when they exist — they're the editable source after first run.
    existing_shards = sorted(BLOCKS_DIR.glob("b*-signal.dat")) if BLOCKS_DIR.exists() else []
    if existing_shards:
        print(f"reading {len(existing_shards)} shard(s) in {BLOCKS_DIR.name}/")
        tracks_by_block = defaultdict(list)
        header_seen = ""
        sep_line = None
        globals_text = None
        # Globals come from blocks/globals.dat (generated previously).
        gtext = read_text(GLOBALS_FILE)
        if gtext:
            _, globals_text, _, _ = parse_signal(gtext, has_globals=True)
            header_seen = ""
            sep_line = detect_sep_line(gtext)
        for shard in existing_shards:
            stext = read_text(shard)
            if not stext:
                continue
            if sep_line is None:
                sep_line = detect_sep_line(stext)
            h, _, tracks, _ = parse_signal(stext, has_globals=False)
            # Derive observed block from filename (b01 → 1).
            m = re.match(r"^b(\d+)-signal\.dat$", shard.name, re.I)
            if not m:
                continue
            observed = int(m.group(1))
            for t in tracks:
                # Placeholders (no `File:` line with a td-audioNNN filename) are
                # scaffolds authors keep pre-positioned so adding a new track is
                # a fill-in rather than a whole-block paste. Preserve them in
                # their observed block — author's placement is respected.
                tracks_by_block[observed].append(t)
        if sep_line is None:
            sep_line = detect_sep_line("")
        return header_seen, globals_text, sep_line, dict(tracks_by_block), "shards"

    # First run — read the master.
    mtext = read_text(SIGNAL_MASTER)
    if mtext is None:
        # Allow archived master if this is being re-run after a rename but shards got nuked.
        mtext = read_text(SIGNAL_MASTER_RENAMED)
        if mtext is None:
            print(f"error: no source signal file found "
                  f"({SIGNAL_MASTER.name} or {SIGNAL_MASTER_RENAMED.name})",
                  file=sys.stderr)
            sys.exit(1)
        print(f"reading archived master ({SIGNAL_MASTER_RENAMED.name}) — "
              f"shards will be rebuilt from it")
    else:
        print(f"first run: reading master ({SIGNAL_MASTER.name})")
    sep_line = detect_sep_line(mtext)
    header, globals_text, tracks, _ = parse_signal(mtext, has_globals=True)
    tracks_by_block = defaultdict(list)
    for t in tracks:
        if not t["tid"]:
            # Placeholder: route to the block hinted by the `# NNN` header in
            # the preamble (e.g. `# 014` → b02). No hint → fall to block 1.
            b = _placeholder_block_for(t)
        else:
            b = block_for(t["tid"]) or 1     # fall back to block 1 for mystery tracks
        tracks_by_block[b].append(t)
    return header, globals_text, sep_line, dict(tracks_by_block), "master"


def archive_master_if_needed():
    """After first run we don't want the SIGNAL master edited anymore (signal
    shards are the editable source, with reorder/conflict reconciliation on
    every re-run). Rename so the author notices. Other masters (rhythm, links,
    skip) stay in place — they're re-sharded from the master on every run, so
    the master is always the source of truth for those."""
    src, dst = SIGNAL_MASTER, SIGNAL_MASTER_RENAMED
    if src.exists() and not dst.exists():
        print(f"archiving  {src.name}  →  {dst.name}  (signal shards are now the editable source)")
        shutil.move(str(src), str(dst))


def _load_master_tracks():
    """Parse the archived master into {tid → {preamble, body}} for content diff.
    Returns {} if archive missing. Placeholder blocks (no File:) are skipped."""
    arch = SIGNAL_MASTER_RENAMED
    if not arch.exists():
        return {}
    mtext = read_text(arch)
    if not mtext:
        return {}
    _, _, tracks, _ = parse_signal(mtext, has_globals=True)
    out = {}
    for t in tracks:
        if t["tid"]:
            out[t["tid"]] = t
    return out


def _load_shard_tracks():
    """Parse every b*-signal.dat shard into {tid → {preamble, body}}. Observed
    block is irrelevant here — we key by track id for straight content diff."""
    out = {}
    if not BLOCKS_DIR.exists():
        return out
    for shard in sorted(BLOCKS_DIR.glob("b*-signal.dat")):
        stext = read_text(shard)
        if not stext:
            continue
        _, _, tracks, _ = parse_signal(stext, has_globals=False)
        for t in tracks:
            if t["tid"]:
                out[t["tid"]] = t
    return out


def _diff_master_vs_shards():
    """Content-level diff between archived master and current shards.
    Returns (added, changed) — lists of tids. Mtime-independent — catches
    edits made to master regardless of when shards were last touched."""
    mtracks = _load_master_tracks()
    stracks = _load_shard_tracks()
    if not mtracks or not stracks:
        return [], []
    added, changed = [], []
    for tid, mt in mtracks.items():
        st = stracks.get(tid)
        if st is None:
            added.append(tid)
            continue
        if _track_fingerprint(mt) != _track_fingerprint(st):
            changed.append(tid)
    return sorted(added, key=lambda t: track_num(t) or 0), \
           sorted(changed, key=lambda t: track_num(t) or 0)


def _sync_from_master(tracks_by_block: dict):
    """Apply master's version of every divergent/new track into tracks_by_block
    (keyed by block number). Run BEFORE reconcile() so downstream flow catches
    any cross-block misplacement. Mutates tracks_by_block; returns list of
    (tid, 'added'|'updated') tuples for the summary."""
    mtracks = _load_master_tracks()
    stracks = _load_shard_tracks()
    applied = []
    for tid, mt in mtracks.items():
        st = stracks.get(tid)
        same = st and _track_fingerprint(mt) == _track_fingerprint(st)
        if same:
            continue
        # Rightful block for this tid. Master is authoritative for content.
        b = block_for(tid) or 1
        bucket = tracks_by_block.setdefault(b, [])
        # Replace-in-place if a track with same tid already exists in bucket;
        # otherwise append. Other blocks' stale copies are caught by reconcile()
        # afterwards (it moves misplaced tracks + detects cross-block dups).
        dup_idx = next((i for i, t in enumerate(bucket) if t["tid"] == tid), None)
        if dup_idx is None:
            bucket.append(mt)
            applied.append((tid, "added"))
        else:
            bucket[dup_idx] = mt
            applied.append((tid, "updated"))
    # Also drop tracks from other blocks that have the same tid but stale
    # content — prevents reconcile from seeing a phantom dup in the wrong block.
    touched_tids = {tid for tid, _ in applied}
    for b, bucket in list(tracks_by_block.items()):
        correct = block_for(bucket[0]["tid"]) if bucket else None
        # only prune non-rightful blocks
        tracks_by_block[b] = [
            t for t in bucket
            if not (t["tid"] in touched_tids and (block_for(t["tid"]) or 1) != b)
        ]
    return applied


def _warn_stale_master(sync_requested: bool):
    """Detect any content divergence between the archived master and the shards.
    Mtime-agnostic. When --sync-from-master is passed, the caller does the merge
    after this prints; otherwise we just warn and let the author decide."""
    arch = SIGNAL_MASTER_RENAMED
    if not arch.exists():
        return
    added, changed = _diff_master_vs_shards()
    if not added and not changed:
        return
    banner = "SYNCING" if sync_requested else "WARNING"
    print()
    print("*" * 66)
    print(f"  {banner}: {arch.name} diverges from the shards.")
    if added:
        print( "  New in master (missing from shards):")
        for tid in added:
            b = block_for(tid) or 1
            print(f"    • {tid}  → should land in  b{b:02d}-signal.dat")
    if changed:
        print( "  Changed in master (shard has older content):")
        for tid in changed:
            b = block_for(tid) or 1
            print(f"    • {tid}  → b{b:02d}-signal.dat")
    if sync_requested:
        print( "  → syncing master edits into shards now.")
    else:
        print()
        print( "  Shards are the editable source — edits to the master are not")
        print( "  auto-merged. Either:")
        print( "    • re-apply your edit directly to the listed bNN-signal.dat,")
        print( "    • OR re-run:  python build-blocks.py --sync-from-master")
    print("*" * 66)
    print()


def main():
    BLOCKS_DIR.mkdir(exist_ok=True)

    sync_requested = ("--sync-from-master" in sys.argv)
    _warn_stale_master(sync_requested)

    # ── 1. Signal: load + reconcile ────────────────────────────────
    header, globals_text, sep_line, tracks_by_block, source = gather_signal_tracks()

    # Optional master→shard sync, applied BEFORE reconcile so downstream
    # reconciliation catches any cross-block misplacement from the merge.
    if sync_requested and source == "shards":
        applied = _sync_from_master(tracks_by_block)
        for tid, kind in applied:
            b = block_for(tid) or 1
            print(f"  [sync] {tid}: {kind} in b{b:02d}-signal.dat from master")

    if source == "shards":
        warnings = reconcile(tracks_by_block)
        for w in warnings:
            print("  " + w)
    else:
        # First run — tracks already grouped by rightful block via block_for().
        # Still sort each bucket by track number so output is ordered.
        for b in tracks_by_block:
            tracks_by_block[b].sort(key=lambda t: t.get("num") or 10**9)

    # ── 2. Signal shards: write each block + globals ──────────────
    written_signal = {}
    # Choose a consistent header for the shards — generated notice.
    shard_header = (
        "# generated by build-blocks.py — edit to add/move tracks, then re-run\n"
        "# misplaced tracks get relocated automatically on next run\n"
    )
    for block, tracks in sorted(tracks_by_block.items()):
        out = emit_signal_shard(shard_header, tracks, sep_line)
        path = BLOCKS_DIR / shard_name("signal", block)
        write_text(path, out)
        # Only real tracks (tid-bearing) count toward the manifest track-count.
        # Placeholders are author scaffolds, not library entries.
        written_signal[block] = [t["tid"] for t in tracks if t["tid"]]

    # Globals file — stays identical across runs unless cycler.tick / etc. change.
    if globals_text is not None:
        g_header = (
            "# generated by build-blocks.py — globals extracted from cf-signal.dat\n"
        )
        write_text(GLOBALS_FILE, emit_globals(g_header, globals_text, sep_line))

    # ── 3. Rhythm / links / skip: shard masters ───────────────────
    rhythm_shards = shard_rhythm(read_text(RHYTHM_MASTER) or "", written_signal)
    skip_shards   = shard_skip  (read_text(SKIP_MASTER)   or "")
    # Links master may be under the archived name on second+ run.
    links_text = read_text(LINKS_MASTER) or read_text(LINKS_MASTER_RENAMED) or ""
    links_shards  = shard_links (links_text)

    for block, text in rhythm_shards.items():
        write_text(BLOCKS_DIR / shard_name("rhythm", block), text)
    for block, text in links_shards.items():
        write_text(BLOCKS_DIR / shard_name("links", block), text)
    for block, text in skip_shards.items():
        write_text(BLOCKS_DIR / shard_name("skip", block), text)

    # ── 4. Clean up stale shards from deleted blocks ──────────────
    all_blocks = set(written_signal) | set(rhythm_shards) | set(links_shards) | set(skip_shards)
    for existing in BLOCKS_DIR.glob("b*-*.dat"):
        m = re.match(r"^b(\d+)-(\w+)\.dat$", existing.name, re.I)
        if not m:
            continue
        bnum = int(m.group(1))
        kind = m.group(2).lower()
        # signal shard is the source of truth — only delete non-signal shards if that
        # kind isn't present for this block now.
        keep = False
        if kind == "signal":
            keep = bnum in written_signal
        elif kind == "rhythm":
            keep = bnum in rhythm_shards
        elif kind == "links":
            keep = bnum in links_shards
        elif kind == "skip":
            keep = bnum in skip_shards
        if not keep:
            print(f"removing stale shard  {existing.name}")
            existing.unlink()

    # ── 5. Write blocks/index.dat manifest ────────────────────────
    manifest_lines = [
        "# generated by build-blocks.py — block manifest for the Player boot",
        "# Format: <block>:<present files>   (signal always implicit; listed for clarity)",
        "# Player fetches blocks/globals.dat + one random block's shards on load,",
        "# then fetches additional blocks on wildcard SCAN (every 3rd) or code unlock.",
        "# Placeholder-only blocks (author scaffolds with no real tracks yet) are",
        "# NOT listed — the Player would pick one and hit an empty Registry.tracks.",
    ]
    for block in sorted(all_blocks):
        count = len(written_signal.get(block, []))
        if count <= 0:
            # Placeholder-only block. Shard file(s) still on disk for authors
            # to edit into, but not advertised to the Player until real tracks
            # land (next build emits a real manifest line for it).
            continue
        present = ["signal"]
        if block in rhythm_shards: present.append("rhythm")
        if block in links_shards:  present.append("links")
        if block in skip_shards:   present.append("skip")
        manifest_lines.append(f"{block:02d}:{','.join(present)}:{count}")
    write_text(INDEX_FILE, "\n".join(manifest_lines) + "\n")

    # ── 6. Archive the master file whenever it's still present. Idempotent —
    #    the helper itself checks `src.exists() AND not dst.exists()` so
    #    repeat runs don't clobber an earlier archive. Runs on both the
    #    master-source and shards-source paths so a leftover master from a
    #    crashed-previous-run doesn't linger alongside the shards.
    archive_master_if_needed()

    # ── 7. Summary ────────────────────────────────────────────────
    print()
    print(f"wrote {len(written_signal)} signal shard(s), "
          f"{len(rhythm_shards)} rhythm shard(s), "
          f"{len(links_shards)} links shard(s), "
          f"{len(skip_shards)} skip shard(s)")
    print(f"manifest: {INDEX_FILE}")
    # Count placeholders per block (not included in manifest counts but useful
    # to surface in the summary so authors can see their scaffolds survived).
    ph_counts = {b: sum(1 for t in ts if _is_placeholder(t)) for b, ts in tracks_by_block.items()}
    for block in sorted(all_blocks):
        tids = written_signal.get(block, [])
        extras = []
        if block in rhythm_shards: extras.append("rhythm")
        if block in links_shards:  extras.append("links")
        if block in skip_shards:   extras.append("skip")
        extras_str = ("  +" + "+".join(extras)) if extras else ""
        ph = ph_counts.get(block, 0)
        ph_str = f"  + {ph} placeholder(s)" if ph else ""
        print(f"  b{block:02d}: {len(tids)} track(s){extras_str}{ph_str}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
